version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scraper:
    build: ./scraper
    container_name: scraper
    depends_on:
      - mongodb
  flask:
    build: ./flask_app
    ports:
      - "5000:5000"
    container_name: flask
    depends_on:
      - mongodb

volumes:
  mongo_data:

